#!/bin/sh
set -e

CONFIG="$HOME/.config/ci"

# TODO:
# .ci and ci init - local configuration file with jenkins url, job name and params
# automatic branch detection
# checking if branch was not pushed or has local changes
#

# Defining colors.
if [ -t 1 ]; then
    NCOLORS=`tput colors`

    if [ -n "$NCOLORS" ] &&  [ $NCOLORS -ge 8 ]; then
        NORMAL=`tput sgr0`
        RED=`tput setaf 1`
        GREEN=`tput setaf 2`
        YELLOW=`tput setaf 3`
        BLUE="$(tput setaf 4)"
        UNDERLINE="$(tput smul)"
    fi
fi

function usage() {
    echo "Usage:"
    echo "    ci JOB_NAME [PARAM=VALUE] - builds job with optional parameters"
}

function run() {
    if [[ $# < 1 ]]; then
        usage
        return
    fi
    source $CONFIG

    JOB_NAME=$1
    shift 1

    PARAMS=""
    for arg in $@; do
        NAME=${arg%=*}
        VALUE=${arg##*=}
        if [ "$PARAMS" ]; then
            PARAMS+=","
        fi
        PARAMS+="{\"name\":\"$NAME\", \"value\":\"$VALUE\"}"
    done
    echo "Building ${YELLOW}$JOB_NAME${NORMAL}: $@"

    JENKINS_CRUMB=$(curl -s --user $JENKINS_CREDENTIALS "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
    RESULT_FILE=`mktemp`
    curl -s -X POST $JENKINS_URL/job/$JOB_NAME/build --user $JENKINS_CREDENTIALS \
                   --data-urlencode json="{\"parameter\": [$PARAMS]}" -H $JENKINS_CRUMB > $RESULT_FILE
    if [ ! -z "$(cat $RESULT_FILE)" ]; then
        ERROR=`cat $RESULT_FILE | pup '#error-description pre text{}' | head -n1 | sed 's/[a-zA-Z.]*: //'`
        echo "${RED}FAIL${NORMAL}: ${RED}$ERROR${NORMAL}"
        rm $RESULT_FILE
        exit 1
    fi
    rm $RESULT_FILE

    RESULT="null"
    while [ "$RESULT" = "null" ]; do
        sleep 1
        LOG=`curl -s $JENKINS_URL/job/$JOB_NAME/lastBuild/api/json --user $JENKINS_CREDENTIALS \
                  -H $JENKINS_CRUMB`
        RESULT=`echo $LOG | tr -d '\n' | jq -r '.result'`
        printf "."
    done
    if [ "$RESULT" != "SUCCESS" ]; then
        echo "${RED}$RESULT${NORMAL}"
        URL=$(echo $LOG | tr -d '\n' | jq -r '.url')
        if [ ! -z "$URL" ]; then
            echo "More info here: ${BLUE}${UNDERLINE}${URL%/}/console${NORMAL}"
        fi
    else
        echo "${GREEN}SUCCESS${NORMAL}"
    fi
}

function createConfig() {
    echo "Please answer few questions:\n"
    read -p $'What is your Jenkins URL? (e.g. http://jenkins.org)\n' JENKINS_URL
    read -p "Username: " JENKINS_LOGIN
    read -p "Password: " -s JENKINS_PASSWORD
    echo "\nValidating..."

    JENKINS_CREDENTIALS="$JENKINS_LOGIN:$JENKINS_PASSWORD"
    set -x +e
    curl -v -s --user $JENKINS_CREDENTIALS "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"
    RESULT=$?
    set +x -e
    if [ ! $RESULT = 0 ]; then
        echo "\nOh no! Let's try again."
        createConfig
        return
    fi

    echo "Success!"

    cat > $CONFIG <<-EOM
JENKINS_URL='$JENKINS_URL'
JENKINS_CREDENTIALS='$JENKINS_LOGIN:$JENKINS_PASSWORD'
EOM
    echo "Your config has been saved at $CONFIG"
}

if [ -f $CONFIG ]; then
    run $@
else
    echo "No configuration file found at $CONFIG"
    createConfig
fi
